apiVersion: v1
kind: Service
metadata:
  name: mydb
  namespace: cloud-park
  labels:
    app: mydb
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  type: LoadBalancer
  clusterIP: None
  selector:
    app: mydb

