apiVersion: v1
kind: Service
metadata:
  name: kukie-portal
  namespace: cloud-park
  labels:
    app: kukie-portal
    knoxid: cloud-park
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30003
  selector:
    app: kukie-portal
    knoxid: cloud-park
